// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Dom2 = require("../dom/Dom2.bs.js");
var Js_array = require("rescript/lib/js/js_array.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function genDishFormInnerHtml(dishes) {
  var dishesStrList = dishes.map(function (dish) {
        return "\n    <option value=\"" + dish.name + "\">" + dish.name + "</option>\n  ";
      });
  return "\n    <label>Please Select a Dish</label>\n    <select>" + Js_array.joinWith("", dishesStrList) + "</select>\n    <label>Please enter no. of servings</label>\n    <input type=\"number\" id=\"people_number\" />\n  ";
}

function genDishFormNode(dishes) {
  return Dom2.createElementByInnerHTML("li", genDishFormInnerHtml(dishes));
}

function genDishFormOuterHtml(dishes) {
  return "<li>" + genDishFormInnerHtml(dishes) + "</li>";
}

function getDishItems(param) {
  var items = [];
  var nodes = Dom2.getChildrenByTagName("servings", "li");
  for(var i = 0 ,i_finish = nodes.length; i < i_finish; ++i){
    var node = Belt_Option.getExn(Caml_option.nullable_to_opt(nodes.item(i)));
    var select = Caml_array.get(node.getElementsByTagName("select"), 0);
    var input = Caml_array.get(node.getElementsByTagName("input"), 0);
    items.push({
          dish: select.value,
          number: input.value
        });
  }
  return items;
}

function genDishPreviewOuterHtml(servings) {
  var list = servings.map(function (serving) {
        return "<li>" + serving.dish + " - " + serving.number + "</li>";
      });
  return "<ul>" + Js_array.joinWith("", list) + "</ul>";
}

exports.genDishFormInnerHtml = genDishFormInnerHtml;
exports.genDishFormNode = genDishFormNode;
exports.genDishFormOuterHtml = genDishFormOuterHtml;
exports.getDishItems = getDishItems;
exports.genDishPreviewOuterHtml = genDishPreviewOuterHtml;
/* No side effect */
