// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Data = require("./data/Data.bs.js");
var Dom2 = require("./dom/Dom2.bs.js");

var step = {
  contents: 1
};

var state = {
  meal: "",
  people: 1,
  restaurant: ""
};

function renderStep(step) {
  if (step !== 1) {
    return ;
  }
  var meals = Data.getMeals(undefined);
  console.log(meals);
  Dom2.fillOptions("select_meal", meals);
  Dom2.fillInput("people_number", String(state.people));
}

function main(param) {
  renderStep(step.contents);
}

renderStep(step.contents);

exports.step = step;
exports.state = state;
exports.renderStep = renderStep;
exports.main = main;
/*  Not a pure module */
