// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function getData(param) {
  return 1;
}

var data = [{
    id: 1,
    name: "Chicken Burger",
    restaurant: "Mc Donalds",
    availableMeals: [
      "lunch",
      "dinner"
    ]
  }];

var payloadResults = [
  {
    TAG: /* Ok */0,
    _0: {
      data: "hi"
    }
  },
  {
    TAG: /* Ok */0,
    _0: {
      data: "bye"
    }
  },
  {
    TAG: /* Error */1,
    _0: "Something wrong happened!"
  }
];

var ok = {
  TAG: /* Ok */0,
  _0: {
    data: "hi"
  }
};

console.log(ok);

exports.getData = getData;
exports.data = data;
exports.payloadResults = payloadResults;
exports.ok = ok;
/*  Not a pure module */
